---
- name: "Import: Check payara is running"
  import_tasks: roles/payara/tasks/status.yml

- name: "Re-install authn_ldap"
  shell: 'su -l {{ payara_user }} -c "cd /home/{{ payara_user }}/install/authn.ldap; ./setup -vv install"'
  become: true
  become_user: root
  args:
    executable: /bin/bash
  when: payaraStatus.rc == 0
