---

- name: 'Check icat-lucene package'
  stat:
    path: /home/{{ payara_user }}/downloads/icat.lucene-1.1.0-distro.zip
  register: packageResult

- name: 'Download icat-lucene'
  get_url:
    url: https://repo.icatproject.org/repo/org/icatproject/icat.lucene/1.1.0/icat.lucene-1.1.0-distro.zip
    dest: /home/{{ payara_user }}/downloads
    owner: '{{ payara_user }}'
    group: '{{ payara_user }}'
    mode: 0664
  when: packageResult.stat.exists is defined and packageResult.stat.exists == false

- name: 'Check icat-lucene installation'
  stat:
    path: /home/{{ payara_user }}/install/icat.lucene
  register: installationResult

- name: 'Unarchive icat-lucene if not installed'
  unarchive:
    src: /home/{{ payara_user }}/downloads/icat.lucene-1.1.0-distro.zip
    dest: /home/{{ payara_user }}/install
    remote_src: true
    owner: '{{ payara_user }}'
    group: '{{ payara_user }}'
  when: installationResult.stat.exists is defined and installationResult.stat.exists == false

- name: 'Configure icat-lucene setup.properties'
  template:
    src: roles/payara/templates/setup.properties.j2
    dest: /home/{{ payara_user }}/install/icat.lucene/setup.properties
    owner: '{{ payara_user }}'
    group: '{{ payara_user }}'
    mode: 0600
  notify:
  - icat-lucene-handler

- name: 'Configure icat-lucene run.properties'
  template:
    src: templates/run.properties.j2
    dest: /home/{{ payara_user }}/install/icat.lucene/run.properties
    owner: '{{ payara_user }}'
    group: '{{ payara_user }}'
    mode: 0664
  notify:
  - icat-lucene-handler

- name: 'Create icat-lucene data directory'
  file:
    path: /home/{{ payara_user }}/data/lucene
    state: directory
    owner: '{{ payara_user }}'
    group: '{{ payara_user }}'
    mode: 0775

- name: 'Configure icat-lucene logback.xml'
  copy:
    src: files/logback.xml
    dest: /home/{{ payara_user }}/install/icat.lucene/logback.xml
    owner: '{{ payara_user }}'
    group: '{{ payara_user }}'
    mode: 0664
  notify:
  - icat-lucene-handler

- name: 'Setup icat-lucene if not setup'
  import_tasks: tasks/installation.yml
  when: (ansible_local is not defined) or (ansible_local.local is not defined) or (ansible_local.local.{{ heading }} is not defined) or (ansible_local.local.{{ heading }}.icat_lucene is not defined) or (ansible_local.local.{{ heading }}.icat_lucene != 'true')
