- name: "Create a stash directory for assembling configurations"
  file:
    path: /home/{{ payara_user }}/stash
    state: directory
    owner: "{{ payara_user }}"
    group: "{{ payara_user }}"
    mode: 0775

- name: "Create a stash directory for icat-server configs"
  file:
    path: /home/{{ payara_user }}/stash/icat-server
    state: directory
    owner: "{{ payara_user }}"
    group: "{{ payara_user }}"
    mode: 0775

- name: "Copy over payara setup.properties"
  template:
    src: "{{ role_path }}/../payara/templates/setup.properties.j2"
    dest: /home/{{ payara_user }}/stash/icat-server/1-part
    owner: "{{ payara_user }}"
    group: "{{ payara_user }}"
    mode: 0664

- name: "Copy over icat-server setup.properties via templating [MariaDB]"
  template:
    src: templates/mariadb.setup.properties.j2
    dest: /home/{{ payara_user }}/stash/icat-server/2-part
    owner: "{{ payara_user }}"
    group: "{{ payara_user }}"
    mode: 0644
  when: setupPropertiesResult.stat.exists is defined and setupPropertiesResult.stat.exists == false and (ansible_local.local.instantiations.mariadb is defined and ansible_local.local.instantiations.mariadb == true)

- name: "Copy over icat-server setup.properties via templating [Oracle]"
  template:
    src: templates/oracle.setup.properties.j2
    dest: /home/{{ payara_user }}/stash/icat-server/2-part
    owner: "{{ payara_user }}"
    group: "{{ payara_user }}"
    mode: 0644
  when: setupPropertiesResult.stat.exists is defined and setupPropertiesResult.stat.exists == false and (ansible_local.local.instantiations.mariadb is not defined or ansible_local.local.instantiations.mariadb == false)

- name: "Configure icat-server setup.properties by concatenation of files in the stash"
  assemble:
    src: /home/{{ payara_user }}/stash/icat-server
    dest: /home/{{ payara_user }}/install/icat.server/setup.properties
    delimiter: '\n'
    owner: "{{ payara_user }}"
    group: "{{ payara_user }}"
    mode: 0600
  notify:
    - "icat-server-handler"
